server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/auth/**

        - id: school-service
          uri: lb://school
          predicates:
            - Path=/schools/**
          filters:
            - AuthenticationFilter

        - id: student-service
          uri: lb://student
          predicates:
            - Path=/students/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true