spring:
  application:
    name: student
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      auto-index-creation: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true